### ISSUE TITLE
can not transfer gif

### ISSUE THREAD

**Issue by fudax** [xtyxtyx/sorry#10]
Errno::ENOENT at /sorry/make
No such file or directory @ rb_sysopen - temp/b244dda3e47566312e22505de0b409b8.gif

$ gem install bundler                     
Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Installing ri documentation for bundler-1.16.1
Done installing documentation for bundler after 6 seconds
1  gem installed

$ gem install ffmpeg
Fetching: ffmpeg-0.2.5.gem (100%)
Successfully installed ffmpeg-0.2.5
Parsing documentation for ffmpeg-0.2.5
Installing ri documentation for ffmpeg-0.2.5
Done installing documentation for ffmpeg after 0 seconds
1 gem installed

[fudax@fudax sorry]$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Using bundler 1.16.1
Fetching daemons 1.2.6
Installing daemons 1.2.6
Fetching eventmachine 1.2.5
Installing eventmachine 1.2.5 with native extensions
Fetching mustermann 1.0.2
Installing mustermann 1.0.2
Fetching rack 2.0.4
Installing rack 2.0.4
Fetching rack-protection 2.0.1
Installing rack-protection 2.0.1
Fetching tilt 2.0.8
Installing tilt 2.0.8
Fetching sinatra 2.0.1
Installing sinatra 2.0.1
Fetching thin 1.7.2
Installing thin 1.7.2 with native extensions
Bundle complete! 2 Gemfile dependencies, 9 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ ruby src/sorry.rb  
== Sinatra (v2.0.1) has taken the stage on 3389 for development with backup from Thin
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:3389, CTRL+C to stop

**Comment by xtyxtyx** [comment]
看起来是没有安装ffmpeg

```
# Ubuntu
apt install ffmpeg

# CentOS
yum install ffmpeg
```

**Comment by fudax** [comment]
solved，光gem install没用，需要yum install
