### ISSUE TITLE
有合并python版的计划么？

### ISSUE THREAD

**Issue by East196** [xtyxtyx/sorry#12]
我刚参照sorry写了个Python版的能合并进来么？[sorrypy](https://github.com/East196/sorrypy)

**Comment by xtyxtyx** [comment]
其实这个项目最早是用crystal语言写的

结果有内存泄漏，就改用了ruby

现在我正在用racket语言重写这个网站，就不合并python版了

已经把你的项目地址加到主页上了，也欢迎你继续开发😁

**Comment by East196** [comment]
O(∩_∩)O哈哈~ 好的，谢谢 @xtyxtyx
