### ISSUE TITLE
点击生成失败

### ISSUE THREAD

**Issue by poaqaqaq** [xtyxtyx/sorry#14]
按照教程安装所需软件，ruby,ffmpeg等，点击生成，出现如下错误

Errno::ENOENT at /sorry/make
No such file or directory @ rb_sysopen - temp/474217342e83ceb6b25573205a175529.gif
file: fileutils.rb location: initialize line: 1289
....
...

**Comment by xtyxtyx** [comment]
看起来是系统中没有安装ffmpeg

在shell中敲下`ffmpeg -version`看看有没有输出？

也可以按照README中的操作使用docker部署

**Comment by poaqaqaq** [comment]
嗯，是我ffmpeg版本太落后的原因

**Comment by poaqaqaq** [comment]
如果ffmpeg想用特别路径，请问要怎么修改，例如想要使用/home/test/ffmpeg这个路径下的ffmpeg？

**Comment by xtyxtyx** [comment]
现在可以修改[site_config.yml](https://github.com/xtyxtyx/sorry/blob/40f34abdc4757bd283f2f412662d6b0a308d103b/site_config.yml#L24)来指定ffmpeg的路径了
