### ISSUE TITLE
有CentOS6的教程么

### ISSUE THREAD

**Issue by 493Arceus** [xtyxtyx/sorry#15]
刚入CentOS的坑没多久，安装ruby各种报错；-；
![image](https://user-images.githubusercontent.com/17383497/37285331-b347d7fc-2639-11e8-97e2-61d070312e4d.png)

**Comment by WalterMa** [comment]
为什么不试试Docker呢？

**Comment by 493Arceus** [comment]
Docker用的是apt啊(｀・ω・´)
CentOS是yum
难道说只能换环境么

**Comment by xtyxtyx** [comment]
如果使用docker，在centOS也可以部署
