### ISSUE TITLE
压缩方法

### ISSUE THREAD

**Issue by CoXier** [xtyxtyx/sorry#16]
我尝试了下面的方法，对输出的 gif 进行了压缩。

对输入视频：

* 移除 audio
* 1.25 倍速度播放
* resize

对生成 gif:
* gifsicle 压缩优化

经过上面的尝试，我还是只能把 sorry 系列压缩成 1.5MB 还是略大。请问还有哪些点可以优化呢？

**Comment by song1090** [comment]
http://www.soogif.com/compress
这个网站是微信GIF压缩专用，可以一键压缩到1M以下。我也想发微信表情，但我不知道应该怎样对生成GIF前的视频进行压缩。图片不清晰一点没关系，但如果加入文字生成GIF后再压缩的话 文字就看不清了。可以麻烦你指点一下压缩视频的教程 或者你把视频压缩好后上传发一个新的链接吗？

**Comment by xtyxtyx** [comment]
感谢关注哈😘

这几天我也在想微信兼容的问题

现在生成的gif规格是300宽度8帧
如果降到240宽度 6帧可以把gif体积降至1M以下
就像下面这张
![gif](https://user-images.githubusercontent.com/15033141/37315148-207c5b50-2693-11e8-98a2-011092e938e4.gif)
然后稍稍加大字号
![gif](https://user-images.githubusercontent.com/15033141/37315227-8c05af48-2693-11e8-83a0-c0a5b5d89b54.gif)

想知道你们觉得这种效果是否满意

如果ok的话我就把这个功能加到网站里

谢谢!😁

**Comment by song1090** [comment]
做得太好了，我很喜欢，谢谢你！其实这是我第一次玩GIF，你做的这个太好玩了😄

**Comment by song1090** [comment]
我觉得你把图像规格缩小、字体放大的效果很不错！

**Comment by song1090** [comment]
对了，请问您大约什么时候可以把小尺寸的GIF模板上传呢？我只是想问一下，您慢慢做 不着急的。

**Comment by song1090** [comment]
你好，请问您的微信兼容现在已经做好了吗？我看现在有一个可以打钩的框框写着微信兼容，但是我打了勾之后做出来的GIF还是1.9M，是不是我的操作不对啊？

谢谢😊

**Comment by xtyxtyx** [comment]
我猜是你的浏览器缓存了旧的JavaScript脚本
试试清空浏览器缓存？
________________________________

**Comment by song1090** [comment]
谢谢，我可以做小图片了。不过我刚是用Safari浏览器做的，用Safari点击微信小图后尺寸大小正好是1M。但我用的Chrome浏览器就不行，点击微信兼容下载后还是1.9M，我清空了历史记录和Cache也不行。
