### ISSUE TITLE
惊了 这也开源 来分享一下喽

### ISSUE THREAD

**Issue by jiagainiunai** [xtyxtyx/sorry#17]
![default](https://user-images.githubusercontent.com/24694640/37507672-be148286-292a-11e8-854e-92ccdc945d66.gif)

**Comment by xtyxtyx** [comment]
![img](https://user-images.githubusercontent.com/15033141/37579868-ad8af78a-2b7b-11e8-8690-c8e292e642aa.GIF)

**Comment by zhonggz** [comment]
要笑死，哈哈哈
