### ISSUE TITLE
关于internal server error

### ISSUE THREAD

**Issue by kaixiaohang** [xtyxtyx/sorry#23]
/app/src/sorry/make_gif.rb:55:in `render_ass'
        /app/src/sorry/make_gif.rb:29:in `make_gif_with_ffmpeg'
        /app/src/sorry/make_gif.rb:67:in `render_gif'
        src/sorry.rb:57:in `block in <main>'
用docker容器建的，反馈中摘取这些，可能有用的信息。

**Comment by nisiyu** [comment]
我也遇到了，你是不是有这个报错？我也是通过docker建的
Encoding::CompatibilityError - incompatible character encodings: ASCII-8BIT and UTF-8

**Comment by nisiyu** [comment]
@kaixiaohang 我看似乎是template.ass这个文件的编码问题，现在是UTF-8 with BOM的编码，我改成了UTF-8就好了，把templates目录里的各种template.ass文件修改一下编码为UTF-8就行 #27

**Comment by kaixiaohang** [comment]
@nisiyu 感谢。

**Comment by xtyxtyx** [comment]
现在可以了么?

**Comment by kaixiaohang** [comment]
@xtyxtyx 
还有一个问题，没提示UTF-8，也是internal server error

**Comment by kaixiaohang** [comment]
我更新最近的版本，重建试试

**Comment by kaixiaohang** [comment]
@xtyxtyx 还是要手动改ass的utf-8 无bom
