### ISSUE TITLE
优化gif输出画质和体积

### ISSUE THREAD

**Issue by celeron533** [xtyxtyx/sorry#25]
1. 预先计算色板，在有限的色彩空间内放下更多的使用到的颜色
2. 减少色板数量，直接减小体积（但是色彩过渡会不自然）
3. 优化选择画面抖动算法，使色彩过渡更加柔和

以前在windows平台下写过个类似的脚本，使用了以上提到的优化方案
https://github.com/celeron533/GIFConverter/blob/master/GIFConverter.cmd

Sample
- fps=15
- resolution: width=128px, height=auto
- dither: none
- duration: 7.5s
- size: 541KB

![Sample gif - Evangelion](https://github.com/celeron533/GIFConverter/blob/master/sample_15fps_128px_none.gif?raw=true)

https://github.com/celeron533/GIFConverter/blob/master/README.md

**Comment by li24361** [comment]
执行一次要多久呢？

**Comment by celeron533** [comment]
测试了一下。。。
体积没有优势
画质有一定的改观

-----
按照目前直接把MP4塞给ffmpeg输出gif
1902kb
![standard](https://user-images.githubusercontent.com/3608762/37712343-942c8090-2d4e-11e8-8c9b-4d2cf32e2cfe.gif)
```
```
-----
调优后的gif
2600kb
![template](https://user-images.githubusercontent.com/3608762/37712367-a02b18d4-2d4e-11e8-937d-c33430351fce.gif)
```
Filters  : fps=8,scale=300:-1:flags=lanczos
MaxColors: 85
Dither   : none
```
-----
极佳画质gif
3505kb
![template](https://user-images.githubusercontent.com/3608762/37712621-634c8f32-2d4f-11e8-97d8-fa3b07c6b74d.gif)
```
[INFO] Filters  : fps=10,scale=300:-1:flags=lanczos
[INFO] MaxColors: 130
[INFO] Dither   : sierra2
```
-----
缩小画质gif
1771kb
![template](https://user-images.githubusercontent.com/3608762/37712721-b44a97ee-2d4f-11e8-9456-8b30ef1f8de2.gif)
```
[INFO] Filters  : fps=8,scale=240:-1:flags=lanczos
[INFO] MaxColors: 80
[INFO] Dither   : none
```

**Comment by xtyxtyx** [comment]
学习了，3Q😘

**Comment by celeron533** [comment]
@li24361 
>执行一次要多久呢？

和原来的相比可能需要3倍时间

**Comment by CoXier** [comment]
因为可能需要更快的返回给用户，所以三倍的时间可能不合适。
