### ISSUE TITLE
能否用Php实现

### ISSUE THREAD

**Issue by ww7752** [xtyxtyx/sorry#28]
能否用Php实现

**Comment by a1392220236** [comment]
+1

**Comment by xtyxtyx** [comment]
关键是我不会写php啊。。。

如果你会php，可以参照现有的几个版本实现php版，并且你愿意的话我会把你的项目放到主页上

**Comment by PrintNow** [comment]
你要的PHP版本：[GitHub](https://github.com/PrintNow/php-sorry-gif)
