### ISSUE TITLE
无法显示中文

### ISSUE THREAD

**Issue by rainbowtrash2333** [xtyxtyx/sorry#3]
<p>不输入任何句子, 就用默认的句子, 直接点击 "生成" 按钮, 生成的.gif 能正常显示中文, </p> 
<p>而输入中文句子,  则.gif 只能显示英文, 不能显示中文.</p>
<p>搭建环境: centos 7 , ruby 2.5.0 , 已安装中文包</p>

**Comment by rainbowtrash2333** [comment]
重新安装中文字体包后问题决绝, (感谢脸)

**Comment by CoXier** [comment]
可以 Close 了
