### ISSUE TITLE
点生成无反应

### ISSUE THREAD

**Issue by ztjryg4** [xtyxtyx/sorry#30]
按照步骤部署在自己的服务器上之后，网页显示正常，ruby src/sorry.rb运行之后在网页上操作，点生成无反应。求大佬指导，是有哪里还需要改动吗？

**Comment by xtyxtyx** [comment]
可以截一段日志发上来吗？

**Comment by ztjryg4** [comment]
![_20180323015212](https://user-images.githubusercontent.com/25434679/37788616-d758be94-2e3c-11e8-9ae6-27afb4c29a5a.png)
感谢回复！这是ruby src/sorry.rb运行之后的信息。是0.0.0.0:4567这个没有设置到位吗？

**Comment by xtyxtyx** [comment]
看起来ffmpeg的版本比较旧

试试装个新版？

**Comment by 493Arceus** [comment]
安装ffmpeg3.4.2
参考sorry的python重置版安装:https://github.com/East196/sorrypy
亲测适用CentOS6
生成无文字的话记得装中文字体
