### ISSUE TITLE
页面优化

### ISSUE THREAD

**Issue by Hunlongyu** [xtyxtyx/sorry#32]
1. 点击生成，没有预览图。
2. 点击下载，打开新的页面，并没有立即下载，还需要另存为。
![_meitu_0](https://user-images.githubusercontent.com/15273630/37747391-e82d8a48-2db9-11e8-8616-b04e0ec76a63.jpg)
```html
<div id="result"> 
    <p><img src="/cache/9de545329f799d7db6b1e8cd600889b6.gif"></p>
    <p><a href="/cache/9de545329f799d7db6b1e8cd600889b6.gif" download="">点击下载</a></p>
    <p></p>
</div>
```
把原来的代码里的第一个 a 标签改成 img 就可以预览了。
第二个a 里面加上 download 属性，就可以直接下载了。

**Comment by li24361** [comment]
download属性支持不完全
如果要预览，可能会造成卡顿
参考：http://118.24.58.55

**Comment by xtyxtyx** [comment]
@li24361  +1
