### ISSUE TITLE
求模板：我不是针对你，我是说在座的各位.gif

### ISSUE THREAD

**Issue by mercury233** [xtyxtyx/sorry#35]

**Comment by li24361** [comment]
https://txtxtx.com.cn/

**Comment by celeron533** [comment]
欢迎提交pull request，不会代码没关系，能提取出视频文件片段和单曲的字幕文件就是很大的帮助了

**Comment by li24361** [comment]
https://txtxtx.com.cn

**Comment by CoXier** [comment]
see https://github.com/xtyxtyx/sorry/issues/59
