### ISSUE TITLE
为什么生成后点下载出来的是空白页面

### ISSUE THREAD

**Issue by 493Arceus** [xtyxtyx/sorry#45]
生成的文件大小为0byte，是权限不够么
CentOS 6.9
![image](https://user-images.githubusercontent.com/17383497/37940775-1bc14fc0-319d-11e8-8111-96af3a4214ca.png)

**Comment by xtyxtyx** [comment]
可以把日志贴上来吗？

**Comment by 493Arceus** [comment]
emmmmm找不到日志文件在哪里

**Comment by 493Arceus** [comment]
不知道这个算不算
![image](https://user-images.githubusercontent.com/17383497/37967380-ba7dbc88-31fd-11e8-83f8-011cd0eeba6b.png)

**Comment by xtyxtyx** [comment]
看起来是你的ffmpeg版本比较低

试试参照这篇文章安装ffmpeg？https://github.com/East196/sorrypy

**Comment by 493Arceus** [comment]
emmmmm,更新到3.4.2了，但是无字幕，是编译的时候缺少模块了么，不知道要什么模块……
![image](https://user-images.githubusercontent.com/17383497/38284142-543036a0-37ec-11e8-923d-10dc96e886fc.png)

**Comment by PrintNow** [comment]
命令行执行 ffmpeg -version 截图

**Comment by PrintNow** [comment]
加上这个
```
./configure --enable-libass
```

**Comment by 493Arceus** [comment]
@PrintNow 上图就是ffmpeg -version的的截图而且已经./configure --enable-libass了:(

**Comment by PrintNow** [comment]
emm，那你安装中文字体了吗？

**Comment by 493Arceus** [comment]
emmmm我貌似明白了什么，我先试试
