### ISSUE TITLE
可不可以自定义图片啊，我不太懂

### ISSUE THREAD

**Issue by 311709000529** [xtyxtyx/sorry#46]

**Comment by CoXier** [comment]
自定义图片是什么意思？你是想自己加视频模板吗？

**Comment by 311709000529** [comment]
对啊

**Comment by 311709000529** [comment]
是可以的吧？？

**Comment by CoXier** [comment]
**暂时不支持自定义模板，如果有好玩的视频模板可以自己制作**

这里有一个 QQ 群专门来收集素材：
![wechatimg113](https://user-images.githubusercontent.com/18747437/37941635-bebc1030-31a1-11e8-969c-3f14ebd3247c.png)


这里有一个小程序 「表情锅」

![](https://t1.aixinxi.net/o_1c9gq5fpcm9t75l7v91ct61voia.jpg-w.jpg)

**Comment by 493Arceus** [comment]
仔细看看下面的介绍，有教你怎么做模板的
