### ISSUE TITLE
【素材提供】朋友，你知道今年新番的1月霸权，人类神经吗？

### ISSUE THREAD

**Issue by ForlornLily** [xtyxtyx/sorry#52]
玩梗哪家强，《pop子与pipi美的日常》不接受反驳，谢谢！
素材在这里：
https://github.com/ForlornLily/node-sorry/tree/dev/public/templates/popteamepic
预览：
<img src = "https://github.com/ForlornLily/node-sorry/raw/dev/img/popteamepic.gif" title="pop team epic">
欢迎大家提供各种梗~

**Comment by shaokeyibb** [comment]
同意啊，希望快点上线

**Comment by CoXier** [comment]
有想要的梗吗？或者字幕

**Comment by CoXier** [comment]
酷安下载 「表情锅」即可制作自定义模板了
