### ISSUE TITLE
大佬，能做一下“勇者喜欢巨乳有什么错”的模板吗

### ISSUE THREAD

**Issue by zimacaoqilai** [xtyxtyx/sorry#53]
勇士闯魔城第一季第六集

**Comment by CoXier** [comment]
有链接吗？

**Comment by zimacaoqilai** [comment]
http://m.iqiyi.com/w_19rqq0skgl.html
22分钟之后，不知道上哪找没字幕水印的。

**Comment by A1exMinatoooo** [comment]
找到无字幕源了，等会儿做个字幕发上来

**Comment by A1exMinatoooo** [comment]
链接：https://pan.baidu.com/s/1l1Ctgxn6I3Y1odRVE-U96A 密码：e363

七天有效，多做了几句，作者看看截取最后一部分做成素材吧23333

**Comment by CoXier** [comment]
@A1exInamin 非常感谢。但是由于此模板不是那么健康，暂时不准备添加模板了。抱歉
