### ISSUE TITLE
sorry的兼容微信的gif

### ISSUE THREAD

**Issue by ghost** [xtyxtyx/sorry#56]
是请求 https://sorry.xuty.tk/api/sorry/wechat/make 吗？
同样的请求这个为啥404
@xtyxtyx

**Comment by xtyxtyx** [comment]
以后会实现，现在只有网页版的api https://sorry.xuty.tk/sorry/wechat/make

你也可以自己改代码然后发个PR，我会把它同步到网站中

**Comment by MikaGuraN** [comment]
@xtyxtyx 看了下js的源码，小图片只是把链接中加了/wechat/
但是java同样的请求，为啥普通链接就可以，请求这个链接就404呢？
