### ISSUE TITLE
[添加模板]我不是针对你，我是说在座的各位都是垃圾

### ISSUE THREAD

**Issue by PrintNow** [xtyxtyx/sorry#59]
我不是针对你，我是说在座的各位都是垃圾：[GitHub](https://github.com/PrintNow/php-sorry-gif/tree/master/templates/dashixiong)
![大师兄。在座的各位都是垃圾](https://gifs.ga/cache/1522848997.gif)

**Comment by CoXier** [comment]
欢迎发 PR

**Comment by PrintNow** [comment]
那我直接发文件好了。
文件过期时间 2018-04-07 12:34：[Firefox Send](https://send.firefox.com/download/87eb0187cf/#AgJ2tx3zsST2NcXJvi1DeQ)
