### ISSUE TITLE
请求添加 爱情公寓2 19集 曾小贤回答连连看的模板

### ISSUE THREAD

**Issue by cherinyy** [xtyxtyx/sorry#61]
请求添加 爱情公寓2 19集 曾小贤回答连连看的模板

**Comment by CoXier** [comment]
close https://sorry.xuty.tk/dati/

**Comment by cherinyy** [comment]
![61b84467618109249cc846d4236f8188](https://user-images.githubusercontent.com/9050713/38464538-e16f3fc2-3b41-11e8-98c5-a1875803bdf7.gif)
![e587143459b632738d6b5251fdbff589](https://user-images.githubusercontent.com/9050713/38464543-ead3d06e-3b41-11e8-9444-5c6d463f6ab0.gif)
