### ISSUE TITLE
写了个 Golang 版本的……

### ISSUE THREAD

**Issue by Hentioe** [xtyxtyx/sorry#64]
各种语言的版本都实现了，于是我就挑了一个暂时没人实现的 Go 语言版。

仓库：https://github.com/Hentioe/sorry-generator

希望能加入这个源头项目 README 的索引中：）

**Comment by xrlin** [comment]
哈哈，看到没有go版本的，刚想开搞补充一个，没想的已经有人写好了。

**Comment by xtyxtyx** [comment]
收到 已经加到README中啦
