### ISSUE TITLE
你好，我做了一个android本地生成，望加入

### ISSUE THREAD

**Issue by ghost** [xtyxtyx/sorry#69]
https://github.com/hl4a/sorry
https://www.coolapk.com/apk/hl4a.sorry

**Comment by CoXier** [comment]
为什么你的项目是用中文开发的。长见识了，哈哈，厉害

**Comment by CoXier** [comment]
由于你的项目不是很规范，暂时不能加入。

**Comment by ghost** [comment]
@CoXier 怎么才算规范呢😂

**Comment by CoXier** [comment]
源码层面：项目代码请尽可能是英文。无法想象一个大项目全用中文会产生什么化学反应。

**Comment by Hentioe** [comment]
666 楼主当初是不是从易语言入门编程的
