### ISSUE TITLE
~

### ISSUE THREAD

**Issue by Ferrum5** [xtyxtyx/sorry#75]
~

**Comment by CoXier** [comment]
很棒呀！
提个建议，可以不用 ffmpeg，也能将 mp4->gif，ffmpeg 这个库还是挺大的。

**Comment by 10000RunningAlpaca** [comment]
试了用MediaMetadataRetriever抽帧，王敬泽的视频测试只能抽出其中两针，也不是微秒的问题，还没找到别的好办法。
