### ISSUE TITLE
用手机标识下的浏览器打开选择时会被跳转

### ISSUE THREAD

**Issue by TemmieFromMars** [xtyxtyx/sorry#76]
我用的是安卓端，神奇浏览器。
刚才试验了一下，在用手机标识进入该网站后切换表情时会被定向跳转到一个色情网站。
然而换成电脑标识就没有这种情况，希望解决一下。:persevere:

**Comment by xtyxtyx** [comment]
网站现在接入了第三方的广告平台，问题大概出自这里

我一直使用ios设备浏览，暂时还没有出现类似的情况

请问现在还会出现类似的问题吗？

如果总是出现的话我会尽快与广告商联系，让他们处理这个问题

**Comment by TemmieFromMars** [comment]
我手机是华为P10plus，在使用华为自带的华为浏览器时不会出现这种情况。昨晚发现这个问题我就卸载了那个神奇浏览器改用了chrome，但是今天用chrome浏览也出现了跳转的情况，是同样的一个色情网站。（在教室被人当成干不正经的事就很尴尬。。 @xtyxtyx
