### ISSUE TITLE
小白提一个 tk 域名的 https 问题

### ISSUE THREAD

**Issue by ghost** [xtyxtyx/sorry#78]
请问您是怎样设置 Github Pages 和 tk 域名的呢？
我使用 Github Pages 和免费的 tk 域名做了个网站   可是并没有 https 的支持
请问您是怎样做的？

@xtyxtyx

**Comment by ghost** [comment]
改了解析以后就好了
~~丢人~~

**Comment by xtyxtyx** [comment]
哈哈 以后遇到问题也欢迎来问哦😜

p.s. 这个网站的https其实是cloudflare提供的
