### ISSUE TITLE
显示英文有问题，中文正常

### ISSUE THREAD

**Issue by TinyQAQ** [xtyxtyx/sorry#9]
生成的.gif 能正常显示中文,但是英文乱码.
搭建环境: centos 7 , ruby 2.5.0 , 已安装中文包

**Comment by xtyxtyx** [comment]
输入英文会显示出什么？

**Comment by TinyQAQ** [comment]
是我系统环境的问题，我重装字体包之后，问题解决了

**Comment by cjydayang** [comment]
@Tiny2009  我也遇到了相同的情况,最开始是中文乱码,安装中文字体后中文正常,但是英文乱码,请问你都安装了什么字体包呢?
